version: "3.7"

services:
    go-demo-app:
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
        # command: go run main.go
        container_name: 'go-demo-app'
        # entrypoint: zsh -c "while sleep 1000; do :; done"
        environment:
            - TZ=
            - GOPATH=/root/go
            - GOTOOLDIR=/root/go/pkg/tool/linux_amd64
        build:
            # This allows us to access higher up files
            context: ..
            dockerfile: .devcontainer/Dockerfile
            # dockerignore: src/github.com/JordanKadish/go_demo/.devcontainer/.dockerignore
        labels:
            com.jordan-kadish.go-demo-app: "basic dockerised Golang env"
        ports:
            - "3000:3000"
        volumes:
            # - ../:/workspace
            # :ro below means "read-only"
            - ~/.ssh:/home/go-demo-app/.ssh:ro
            - ~/.ssh:/root/.ssh:ro
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /root/go
        # links:
        #     - redis
        # networks: 
            # - dev-network
        # redis:
    #     image: redis:alpine
# networks: 
#     dev-network:
#         driver: bridge
